name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python: ['3.9', '3.10', '3.11', '3.12']

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: pip
          # bust cache when deps change
          cache-dependency-path: |
            pyproject.toml
            requirements*.txt

      - run: python -m pip install -U pip
      - run: python -m pip install -e . pytest ruff
      - run: ruff check src
      - run: pytest -q
